# NumPy Exercises 


In [1]:
#Kerim Sever
#IS 465
#Professor Lin
#test1

## Defining an array


#### Import NumPy as np

In [129]:
import numpy as np

#### Create an array of 10 zeros 

In [130]:
array=np.zeros(10)
print("Creating an array of 10 zeros:")
print(array)

Creating an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [131]:
array=np.ones(10)
print("An array of 10 ones: ")
print(array)

An array of 10 ones: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 tens

In [132]:
array=np.ones(10)*10
print("An array of 10 tens: ")
print(array)

An array of 10 tens: 
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


#### Create an array of the integers from 10 to 100

In [133]:
a=np.arange(10,101)
print(a)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### Create an array of all the odd integers from 10 to 30

In [120]:
a = np.array([i for i in range(10, 31) if i%2 != 0])
print(a)

[11 13 15 17 19 21 23 25 27 29]


#### Create a 3x3 array with values ranging from 0 to 8 

In [134]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create an array of 25 random numbers between 0 and 1

In [137]:
a=np.random.rand(25)
print(a)

[0.34749829 0.326225   0.38713134 0.44609202 0.12429799 0.14118259
 0.31248405 0.46557768 0.11227173 0.89678774 0.64991777 0.58778907
 0.07775319 0.72516698 0.56252584 0.87024707 0.91440868 0.00480822
 0.00458745 0.6674795  0.0917557  0.07631485 0.57478336 0.59996951
 0.18198005]


#### Create an array of 40 linearly spaced points between 0 and 10:

In [138]:
a=np.linspace(0, 10, 40)
print(a)

[ 0.          0.25641026  0.51282051  0.76923077  1.02564103  1.28205128
  1.53846154  1.79487179  2.05128205  2.30769231  2.56410256  2.82051282
  3.07692308  3.33333333  3.58974359  3.84615385  4.1025641   4.35897436
  4.61538462  4.87179487  5.12820513  5.38461538  5.64102564  5.8974359
  6.15384615  6.41025641  6.66666667  6.92307692  7.17948718  7.43589744
  7.69230769  7.94871795  8.20512821  8.46153846  8.71794872  8.97435897
  9.23076923  9.48717949  9.74358974 10.        ]


## Indexing 


In [139]:
#You are given the following 2D array
a = np.arange(1,25).reshape(4,-1)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [140]:
# Use array indexing to select the subset that contains 9,10,11,12,15,16,17,18,21,22,23,24. 
# In other words, the 3 * 4 sub-matrix in the bottom right corner of your array
# I have shown you the output -- be careful, if you run your code, it is going to "wipe out" my output
a[1:4,2:]

array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]])

In [141]:
# Use array indexing  get the value 20, as my output shows
a[3,1]

20

In [142]:
# Use array indexing  get the column 10, 16, 22, as my output shows
a[1:4,3:4]

array([[10],
       [16],
       [22]])

In [143]:
# Use array indexing  get the row [15,16,17] as my output shows
a[2:3,2:5]

array([[15, 16, 17]])

### Now the hard task!

#### Write a function that gives the users four random integers between 1 and 10 and ask them to enter the square number of them. If the user answers all of them correctly, congratulate them. Otherwise, show them the right answer

In [149]:
# Step 0: Import numpy -- ALWAYS import all the libraries you need at the beginning!
import numpy as np

#Step 1: Function creation -- refer to the last lab for the syntax of function creation
# does our function take parameters?
# Create your function here:
def squarenumbers():
    
   #Step 2: Create an array of four random integers between 1 and 10 
   num=np.random.choice(np.arange(1,11),4,replace=False)
   #Step 3: Print your numbers
   print(num)

   #Step 4: Prompt the user to enter four numbers, ONE AT A TIME. Use a loop to store these four numbers in a new array
   #  HINT 1: We could take all four numbers in through one line, but to practice loop, let's do it the hard way
   #  HINT 2: You can start by creating an empty array -- np.array([]), then appending to it one at a time
   #  HINT 3: Remember, input() only returns STRINGS. You need to turn them into integers
   squarenumbers=np.array([])
   for i in range(4):
        x=int(input('Enter square of number {:}: '.format(i+1)))
        squarenumbers=np.append(squarenumbers,x)
  
   #Step 5: Now that you have the two arrays, you can compare them using array functions and decide whether the answers are correct
   #  HINT 4: To compare two arrays, you can use array1 == array2 -- however, you have to use a variable to hold the result
   #          The resulted array is an array of Boolean values. To quickly check whether it contains true value, you might want to
   #          use the all() or any() function...
   check=squarenumbers==num**2
   if all(check==True):
       print('Congratulations, all numbers are correct')
   else:
       print('you input the wrong numbers. Here are the correct numbers :',num**2)




    

In [150]:
squares()

[10  9  2  6]
Enter square of number 1: 100
Enter square of number 2: 81
Enter square of number 3: 4
Enter square of number 4: 36
Congratulations, you got all answers correct


In [127]:
squares()

[ 8  2 10  4]
Enter square of number 1: 4
Enter square of number 2: 4
Enter square of number 3: 6
Enter square of number 4: 5
you did not get all answers correct. Here are the correct answers: [ 64   4 100  16]
